### ISSUE TITLE
How to handle unpicked files?

### ISSUE THREAD

**Issue by amiitpatil** [deakjahn/flutter_dropzone#74]
await never resolves if user didn't pick a file
Print statement will not get executed if user closes the picker dialog, also no error is thrown
 
```
Future fun()async{
final files = await _dropzoneController?.pickFiles();
print("reached here");
}
```

cc: @deakjahn

**Comment by deakjahn** [comment]
Could you try this fix?

**Comment by amiitpatil** [comment]
Hi @deakjahn , Thanks for the quick response!

I have set dependancy to latest `a643d6` commit , and tested again after flutter clean and pub get Issue is still reproducible. FYI I'm using chrome.

```
flutter_dropzone:
    git: 
      url: https://github.com/deakjahn/flutter_dropzone.git
      ref: a643d60579214616964e7277d4634ebc5859f8af
      path: flutter_dropzone
```
